# yaml-language-server: $schema=https://raw.githubusercontent.com/awslabs/automated-security-helper/refs/heads/main/automated_security_helper/schemas/AshConfig.json
project_name: my-workspace
global_settings:
  severity_threshold: HIGH
  ignore_paths: []
  suppressions:
    # Terraform state files contain AWS resource IDs, not secrets
    - rule_id: 'SECRET-BASE64-HIGH-ENTROPY-STRING'
      path: 'terraform-dev/terraform.tfstate*'
      reason: 'False positive: Terraform state files contain AWS resource IDs and ARNs, not actual secrets'
    
    - rule_id: 'SECRET-HEX-HIGH-ENTROPY-STRING'
      path: 'terraform-dev/terraform.tfstate*'
      reason: 'False positive: Terraform state files contain AWS resource IDs and ARNs, not actual secrets'
    
    # Additional terraform state file secret types
    - rule_id: 'SECRET-KEYWORD'
      path: 'terraform-dev/terraform.tfstate*'
      reason: 'False positive: Terraform state files contain AWS resource IDs and ARNs, not actual secrets'
    
    - rule_id: 'SECRET-AWS-ACCESS-KEY-ID'
      path: 'terraform-dev/terraform.tfstate*'
      reason: 'False positive: Terraform state files contain AWS resource IDs and ARNs, not actual secrets'
    
    # HTML templates contain SHA384 integrity hashes for CDN security
    - rule_id: 'SECRET-BASE64-HIGH-ENTROPY-STRING'
      path: '*/templates/*.html'
      reason: 'False positive: HTML templates contain SHA384 integrity hashes for Subresource Integrity (SRI), not secrets'
    
    # Checkov CKV_AWS_336 false positives - these services have readonly_root_filesystem = true but still fail
    - rule_id: 'CKV_AWS_336'
      path: 'terraform-dev/05-task-definitions.tf'
      line_range: '40-57'
      reason: 'False positive: DataAPI service has readonly_root_filesystem = true but Checkov still flags it'
    
    - rule_id: 'CKV_AWS_336'
      path: 'terraform-dev/05-task-definitions.tf'
      line_range: '60-77'
      reason: 'False positive: Alerts service has readonly_root_filesystem = true but Checkov still flags it'
    
    # Additional CKV_AWS_336 suppressions for module definition file (ASH reports them here)
    - rule_id: 'CKV_AWS_336'
      path: 'terraform-dev/modules/ecs_task_definition/main.tf'
      line_range: '9-117'
      reason: 'False positive: ECS task definition module - alerts and dataapi services have readonly_root_filesystem = true but Checkov still flags them'
    
    # CKV_SECRET_6 false positives in workshop CloudFormation template
    - rule_id: 'CKV_SECRET_6'
      path: 'workshop/AWS102.yml'
      line_range: '2104-2105'
      reason: 'False positive: Lambda function code contains variable names "token" and "step" from AWS event parameters, not hardcoded secrets'
    
    - rule_id: 'CKV_SECRET_6'
      path: 'workshop/AWS102.yml'
      line_range: '2156-2157'
      reason: 'False positive: Lambda function code contains dictionary key "password" for AWS Secrets Manager rotation, not a hardcoded password'
    
    # Semgrep AWS Account ID detections in terraform state files
    - rule_id: 'generic.secrets.security.detected-aws-account-id.detected-aws-account-id'
      path: 'terraform-dev/terraform.tfstate*'
      reason: 'False positive: Terraform state files contain AWS account IDs as part of resource ARNs, not secrets'
    
    # Semgrep AWS Account ID detections in workshop files
    - rule_id: 'generic.secrets.security.detected-aws-account-id.detected-aws-account-id'
      path: 'workshop/*.yml'
      reason: 'False positive: CloudFormation template contains public AWS service account IDs for ALB access logging (documented by AWS, not customer secrets)'
    
    # Workshop files contain CloudFormation templates with legitimate AWS Secrets Manager references
    - rule_id: 'SECRET-BASE64-HIGH-ENTROPY-STRING'
      path: 'workshop/AWS102.yml'
      reason: 'False positive: CloudFormation template contains legitimate AWS Secrets Manager references and IAM policies, not hardcoded secrets'
    
    - rule_id: 'SECRET-HEX-HIGH-ENTROPY-STRING'
      path: 'workshop/AWS102.yml'
      reason: 'False positive: CloudFormation template contains legitimate AWS Secrets Manager references and IAM policies, not hardcoded secrets'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      reason: 'False positive: CloudFormation template contains legitimate AWS Secrets Manager references and IAM policies, not hardcoded secrets'
    
    - rule_id: 'SECRET-SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      reason: 'False positive: CloudFormation template contains legitimate AWS Secrets Manager references and IAM policies, not hardcoded secrets'
    
    - rule_id: 'SECRET-AWS-ACCESS-KEY-ID'
      path: 'workshop/AWS102.yml'
      reason: 'False positive: CloudFormation template contains legitimate AWS Secrets Manager references and IAM policies, not hardcoded secrets'
    
    # Workshop live file contains CloudFormation templates with legitimate AWS Secrets Manager references
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '767'
      reason: 'False positive: CloudFormation dynamic reference to retrieve secret header name from Secrets Manager - {{resolve:secretsmanager:...}}'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '769'
      reason: 'False positive: CloudFormation dynamic reference to retrieve secret header value from Secrets Manager - {{resolve:secretsmanager:...}}'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '1120'
      reason: 'False positive: IAM policy action "secretsmanager:GetSecretValue" for legitimate secret access permissions'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '1121'
      reason: 'False positive: IAM policy action "secretsmanager:DescribeSecret" for legitimate secret access permissions'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2145'
      reason: 'False positive: Lambda function code calling AWS SDK get_secret_value() method for secret rotation functionality'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2146'
      reason: 'False positive: Lambda function code calling AWS SDK get_secret_value() method for secret rotation functionality'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2152'
      reason: 'False positive: Lambda function code calling AWS SDK get_random_password() method for secret rotation functionality'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2171'
      reason: 'False positive: Lambda function log message containing "secret" keyword in context of AWS secret rotation'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2201'
      reason: 'False positive: Lambda function log message containing "secret" keyword in context of AWS secret rotation'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2216'
      reason: 'False positive: Lambda function log message containing "secret" keyword in context of AWS secret rotation'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2227'
      reason: 'False positive: Lambda function log message containing "secret" keyword in context of AWS secret rotation'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2244'
      reason: 'False positive: Lambda function log message containing "secret" keyword in context of AWS secret rotation'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2316'
      reason: 'False positive: IAM policy actions for Secrets Manager operations (DescribeSecret, GetSecretValue, PutSecretValue, UpdateSecretVersionStage)'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2317'
      reason: 'False positive: IAM policy actions for Secrets Manager operations (GetSecretValue, PutSecretValue, UpdateSecretVersionStage)'
    
    - rule_id: 'SECRET-KEYWORD'
      path: 'workshop/AWS102.yml'
      line_range: '2321'
      reason: 'False positive: IAM policy action "secretsmanager:GetRandomPassword" for legitimate password generation in secret rotation'
    # ASH config file contains suppression reasons that mention "secret" keyword
    - rule_id: 'SECRET-KEYWORD'
      path: '.ash/.ash.yaml'
      line_range: '103'
      reason: 'False positive: ASH suppression reason text mentioning "secret" in context of explaining false positives'
    
    - rule_id: 'SECRET-KEYWORD'
      path: '.ash/.ash.yaml'
      line_range: '108'
      reason: 'False positive: ASH suppression reason text mentioning "secret" in context of explaining false positives'
    
    - rule_id: 'SECRET-KEYWORD'
      path: '.ash/.ash.yaml'
      line_range: '163'
      reason: 'False positive: ASH suppression reason text mentioning "secret" in context of explaining false positives'

fail_on_findings: true
ash_plugin_modules: []
external_reports_to_include: []
build: null
converters:
  archive:
    name: archive
    enabled: true
    options: {}
  jupyter:
    name: jupyter
    enabled: true
    options:
      tool_version: '>=7.16.0,<8.0.0'
      install_timeout: 300
scanners:
  bandit:
    name: bandit
    enabled: true
    options:
      severity_threshold: null
      config_file: null
      confidence_level: all
      ignore_nosec: false
      excluded_paths: []
      additional_formats: []
      tool_version: '>=1.7.0,<2.0.0'
      install_timeout: 300
  cdk-nag:
    name: cdk-nag
    enabled: true
    options:
      severity_threshold: null
      nag_packs:
        AwsSolutionsChecks: true
        HIPAASecurityChecks: false
        NIST80053R4Checks: false
        NIST80053R5Checks: false
        PCIDSS321Checks: false
  cfn-nag:
    name: cfn-nag
    enabled: true
    options:
      severity_threshold: null
  checkov:
    name: checkov
    enabled: true
    options:
      severity_threshold: null
      config_file: null
      skip_path: []
      additional_formats:
      - cyclonedx_json
      offline: false
      frameworks:
      - all
      skip_frameworks: []
      tool_version: null
      install_timeout: 300
  detect-secrets:
    name: detect-secrets
    enabled: true
    options:
      severity_threshold: null
      baseline_file: null
      scan_settings:
        version: null
        generated_at: null
        plugins_used: []
        filters_used: []
        results: {}
  grype:
    name: grype
    enabled: true
    options:
      severity_threshold: null
      config_file: null
      offline: false
  npm-audit:
    name: npm-audit
    enabled: true
    options:
      severity_threshold: null
      offline: false
  opengrep:
    name: opengrep
    enabled: false
    options:
      severity_threshold: null
      config: auto
      exclude:
      - '*-converted.py'
      - '*_report_result.txt'
      exclude_rule: []
      severity: []
      metrics: auto
      offline: false
      patterns: []
      version: v1.1.5
  semgrep:
    name: semgrep
    enabled: true
    options:
      severity_threshold: null
      config: auto
      exclude:
      - '*-converted.py'
      - '*_report_result.txt'
      exclude_rule: []
      severity: []
      metrics: auto
      offline: false
      tool_version: null
      install_timeout: 300
  syft:
    name: syft
    enabled: true
    options:
      severity_threshold: null
      config_file: null
      exclude: []
      additional_outputs:
      - syft-table
reporters:
  csv:
    name: csv
    enabled: true
    options: {}
    extension: csv
  cyclonedx:
    name: cyclonedx
    enabled: true
    options: {}
    extension: cdx.json
  html:
    name: html
    enabled: true
    options: {}
    extension: html
  flat-json:
    name: flat-json
    enabled: true
    options:
      include_scanner_metrics: true
      include_summary_metrics: true
      include_metadata: true
    extension: flat.json
  gitlab-sast:
    name: gitlab-sast
    enabled: true
    options: {}
    extension: gl-sast-report.json
  junitxml:
    name: junitxml
    enabled: true
    options:
      respect_severity_threshold: true
    extension: junit.xml
  markdown:
    name: markdown
    enabled: true
    options:
      include_summary: true
      include_findings_table: false
      include_detailed_findings: true
      max_detailed_findings: 20
      top_hotspots_limit: 10
      use_collapsible_details: true
    extension: summary.md
  ocsf:
    name: ocsf
    enabled: true
    options: {}
    extension: ocsf.json
  sarif:
    name: sarif
    enabled: true
    options: {}
    extension: sarif
  spdx:
    name: spdx
    enabled: false
    options: {}
    extension: spdx.json
  text:
    name: text
    enabled: true
    options:
      include_summary: true
      include_findings_table: false
      include_detailed_findings: false
      max_detailed_findings: 20
      top_hotspots_limit: 20
    extension: summary.txt
  yaml:
    name: yaml
    enabled: false
    options: {}
    extension: yaml
mcp-resource-management:
  max_concurrent_scans: 3
  max_concurrent_tasks: 20
  thread_pool_max_workers: 4
  scan_timeout_seconds: 1800
  operation_timeout_seconds: 180
  shutdown_timeout_seconds: 30
  memory_warning_threshold_mb: 1024
  memory_critical_threshold_mb: 2048
  task_count_warning_threshold: 15
  max_message_size_bytes: 10485760
  max_path_length: 4096
  max_directory_size_mb: 1000
  enable_health_checks: true
  health_check_interval_seconds: 60
  enable_resource_logging: true
  log_resource_operations: false